#!/usr/bin/env python3
"""Print Dart constants from the bundled QWeather mapping to stdout."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'assets/qweather_weather_code_map.json').read_text())
quote = lambda value: json.dumps(value, ensure_ascii=False).replace('$', r'\$')
print('// Generated by scripts/generate_weather_icons.py; do not edit by hand.')
print("import 'package:flutter/widgets.dart';\n")
for section, name in [('regular', 'weatherIcons'), ('filled', 'filledWeatherIcons')]:
    print(f'const {name} = <String, IconData>{{')
    for code, value in data[section].items():
        point = int(value, 16) if isinstance(value, str) else value
        print(f'  {quote(code)}: IconData(0x{point:x}, fontFamily: {quote(data["fontFamily"])}),')
    print('};\n')
print('const weatherDescriptions = <String, String>{')
for code, description in data['descriptions'].items():
    print(f'  {quote(code)}: {quote(description)},')
print('};')
